language: php

php: [5.4, 5.5, 5.6, hhvm]

services: [rabbitmq]

before_script:
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then echo "extension=amqp.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`; fi;'
  - composer selfupdate
  - composer install --prefer-source
